name: Production - Deploy to production environment
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package proxy into a ZIP archive and send to the Deployment API
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          username_ping: ${{ secrets.username_ping }}
          password_ping: ${{ secrets.password_ping }}
          DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          sed -i "s/{username}/$username/g" edge.json
          sed -i "s/{password}/$password/g" edge.json
          sed -i "s/{username_ping}/$username_ping/g" edge.json
          sed -i "s/{password_ping}/$password_ping/g" edge.json
          mkdir deployment
          cp ./edge.json ./deployment
          cp -r ./apiproxy ./deployment/apiproxy
          cd ./deployment
          zip -qq -r ./apigee-proxy-sample.zip .
          unzip -l ./apigee-proxy-sample.zip
          curl --location -i --request PUT "https://api-garden.teliacompany.com/B2X_Global_Apigarden-Pipeline_V1/env/prod/projects/B2X_Lithuania_Lead_Documents_V1" --header "Authorization: $DEPLOYMENT_TOKEN" --header "Content-Type: application/zip" --data-binary "@apigee-proxy-sample.zip"
          curl --location --fail --request GET "https://api-garden.teliacompany.com/B2X_Global_Apigarden-Pipeline_V1/env/prod/projects/B2X_Lithuania_Lead_Documents_V1" --header "Authorization: $DEPLOYMENT_TOKEN"
