# This is a basic workflow to help you get started with Actions

name: Publish to Developers Portal

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - 'specs-*'
jobs:
  validate:
    container: gkarthics/swagger-validate:0.2.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate
        run: validate ./docs
  publish:
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Portal
        env:
          PORTAL_PUBLISHER_TOKEN_URL: ${{ secrets.PORTAL_PUBLISHER_TOKEN_URL }}
        run: |
          curl -vvv -X POST -H 'Content-Type: application/yaml' --fail --data-binary @docs/B2X_Lithuania_Lead_Documents_V1_Specs.yaml "$PORTAL_PUBLISHER_TOKEN_URL"
